server.port=${PORT:8080}
spring.application.name=JobPortal
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/jobportals
spring.datasource.username=postgres
spring.datasource.password=roysonroy19
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true